# Generated by Django 5.2.5 on 2025-08-29 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('department', models.CharField(choices=[('IT', 'IT отдел'), ('HR', 'Отдел кадров'), ('MARKETING', 'Маркетинг'), ('SALES', 'Продажи'), ('FINANCE', 'Финансы'), ('LEGAL', 'Юридический отдел')], max_length=20, verbose_name='Отдел')),
                ('position', models.CharField(choices=[('JUNIOR_DEV', 'Junior разработчик'), ('SENIOR_DEV', 'Senior разработчик'), ('TEAM_LEAD', 'Тимлид'), ('MANAGER', 'Менеджер'), ('DIRECTOR', 'Директор'), ('SPECIALIST', 'Специалист'), ('ANALYST', 'Аналитик')], max_length=20, verbose_name='Должность')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
