version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: erp_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: erp_system
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: Bauka2745

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=128MB
      -c effective_cache_size=512MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp_admin -d erp_system"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: erp-network
    driver: bridge