# Generated by Django 5.2.5 on 2025-08-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название схемы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fields_config', models.JSONField(help_text='JSON с описанием полей таблицы', verbose_name='Конфигурация полей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Схема таблицы',
                'verbose_name_plural': 'Схемы таблиц',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные записи')),
                ('source_service', models.CharField(max_length=50, verbose_name='Сервис-источник')),
                ('source_id', models.CharField(blank=True, max_length=100, verbose_name='ID в сервисе-источнике')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='tables.tableschema', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Данные таблицы',
                'verbose_name_plural': 'Данные таблиц',
                'ordering': ['-created_at'],
            },
        ),
    ]
